# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# Create the Gradio interface
interface = gr.Interface(
    fn=summarize_text,
    inputs=[
        gr.Textbox(lines=10, placeholder="Enter text to summarize..."),  # Text input
        gr.File(file_types=[".txt"], label="Or upload a text file")      # File upload input
    ],
    outputs=gr.Textbox(label="Summarized Text"),
    title="Text Summarization Tool",
    description="Upload a text file or type text to generate a concise summary."
)

# Launch the Gradio interface
interface.launch()