# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# Initialize the summarizer model
summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

# Function for summarizing the input text
def summarize_text(text, file=None):
    if file is not None:
        # If a file is uploaded, read its content
        try:
            # Gradio gives the uploaded file as a NamedTemporaryFile
            with open(file.name, 'r') as f:
                text = f.read()
        except Exception as e:
            return f"Error reading the file: {e}"

    # Perform summarization
    if text:
        summary = summarizer(text, max_length=150, min_length=30, do_sample=False)
        return summary[0]['summary_text']
    else:
        return "No text provided for summarization."